config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "start_stops#index"
  resources :start_stops, only: [:index, :show]
  resources :start, only: [:new, :create]
  resources :stop, only: [:new, :create]
  
 
 



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/timecard.rb
class Timecard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :nickname, presence: true, length: { maximum: 6 }

         has_many :start_stops
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/timecards_controller.rb
class TimecardsController < ApplicationController

  def index
    @start_stop = StartStop.all
  end

  def new
    @start = Start.new
  end

  def create
    @start = Start.new(time_params)
    if @start.save
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def show
    @start_stop = StartStop.find(params[:id])
  end

  private

  def time_params
    params.permit(:start_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timecards_helper.rb
module TimecardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimecardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/start_stops/index.html.erb
<div class = main >
  <div class = top-page >
    <div class = left-bar >
      <% if user_signed_in? %>
        <div class = lists >
          <h1><%= current_user.nickname %></h1>
          <ul>
            <li class = li1><%= link_to "社員登録" %></li>
            <li class = li2><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout" %></li>
          </ul>
        </div>
    </div>

        <div class = right-main >
          <div class = app-name >TIMECARD</div>
          <div>  時間</div>
          <% @timecard.each do |timecard| %>
            <div class = clock >
                 出勤<%= "#{timecard.start_time}"%> 〜退勤<%= "#{timecard.stop_time}" %>
            </div>
          <% end %>
           <div class = buttons >
             <%= button_to '出退勤登録', '#', method: :get, class: "start-work" %> 
           </div>
          
        </div>
  </div>
      <% else %>
        <div class = devise >
          <div class = no-sign-in >
              <h1>TIMECARD</h1>
            <%= link_to "社員登録", new_user_registration_path %>
            <%= link_to "ログイン", new_user_session_path %>
          </div>
        </div>
      <% end %>
</div>

app/views/timecards/_start.html.erb
<div class = buttons >
  <%= button_to '出勤', 'new_start_stop_start_path', method: :get, class: "start-work" %>
</div>

app/views/timecards/_stop.html.erb
<div class = buttons >
  <%= button_to '退勤', '#', method: :get, class: "start-work" %> 
</div>

app/views/timecards/index.html.erb
<div class = main >
  <div class = top-page >
    <div class = left-bar >
      <% if user_signed_in? %>
        <div class = lists >
          <h1><%= current_user.nickname %></h1>
          <ul>
            <li class = li1><%= link_to "時間管理", start_stop_path(@start_stop) %></li>
            <li class = li2><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout" %></li>
          </ul>
        </div>
    </div>

        <div class = right-main >
          <div class = app-name >TIMECARD</div>
          <div class = time >  時間</div>
          <%= render partial: 'start' %>
        </div>
  </div>
      <% else %>
        <div class = devise >
          <div class = no-sign-in >
              <h1>TIMECARD</h1>
            <%= link_to "社員登録", new_user_registration_path %>
            <%= link_to "ログイン", new_user_session_path %>
          </div>
        </div>
      <% end %>
</div>

app/views/timecards/show.html.erb
   <h1>時間管理</h1>
          <% @start_stop.each do |start_stop| %>
            <div class = clock >
                 出勤<%= "#{start_stop.start_time}"%> 〜退勤<%= "#{start_stop.stop_time}" %>
            </div>
          <% end %>